### ISSUE TITLE
[RG 5.1.1] whois_miner throws an SSLError

### ISSUE THREAD

**Issue by T145** [lanmaster53/recon-ng-marketplace#100]
**Module Name**

whois_miner

**Bug Description**

```
--------------------
COMPANY
--------------------
[!] HTTPSConnectionPool(host='whois.arin.net', port=443): Max retries exceeded with url: /rest/org/COMPANY (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_ske_dhe', 'dh key too small')])"))).
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
```

**Steps to Reproduce**

1. Run the module w/ data in the "companies" table

**Expected Behavior**

Module functionality

**Comment by cowboyGibs0n** [comment]
Recon-ng is doing what it supposed to be doing, which is trusting openssl to fail on tls errors. https://whois.arin.net is using a diffie-helman server temp key of 1024-bit, which is smaller than their public key of 2048-bit, a misconfiguration on Arin. Openssl fails when they dh key is too small (less than 1024-bit) or smaller than the public key. Since most public keys are at least 2048-bit, so should the DH key exchange. Why 2048-bit? https://weakdh.org/imperfect-forward-secrecy-ccs15.pdf

You can test this using curl too.
`$ curl -v https://whois.arin.net/
*   Trying 199.212.0.46:443...
* TCP_NODELAY set
* Connected to whois.arin.net (199.212.0.46) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
* Closing connection 0
curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
`
As a temp work around, comment out the last line in /etc/ssl/openssl.cnf
`#CipherString = DEFAULT@SECLEVEL=2`
Then restart recon-ng

**Comment by lanmaster53** [comment]
Awesome! Thanks @cowboyGibs0n!
