### ISSUE TITLE
SyntaxWarnings

### ISSUE THREAD

**Issue by khalil2535** [lanmaster53/recon-ng-marketplace#106]
**Module Name**
Which module is affected?

https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/domains-domains/brute_suffix.py

**Bug Description**

/home/{user}/.recon-ng/modules/recon/domains-domains/brute_suffix.py:28: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  words = [line.strip().lower() for line in fp if len(line)>0 and line[0] is not '#']

**Steps to Reproduce**

marketplace install recon/domains-domains/brute_suffix

**Comment by khalil2535** [comment]
Another warning here too.

**Module Name**
Which module is affected?

https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/domains-hosts/hackertarget.py

**Bug Description**

/home/{user}/.recon-ng/modules/recon/domains-hosts/hackertarget.py:18: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if resp.status_code is not 200:

**Steps to Reproduce**

marketplace install recon/domains-hosts/hackertarget

**Comment by lanmaster53** [comment]
```
[recon-ng][default] > marketplace install recon/domains-domains/brute_suffix
[*] Module installed: recon/domains-domains/brute_suffix
[*] Reloading modules...
[recon-ng][default] > marketplace install recon/domains-hosts/hackertarget
[*] Module installed: recon/domains-hosts/hackertarget
[*] Reloading modules...
[recon-ng][default] > 
```

¯\_(ツ)_/¯ Github obviously does not like requests from your IP address.

**Comment by kpcyrd** [comment]
@lanmaster53 this warning was introduced in python 3.8, the bugs are located here:
https://github.com/lanmaster53/recon-ng-marketplace/blob/bab663d0d7b5bc4f8d55169fcb0b945b716abab5/modules/recon/domains-domains/brute_suffix.py#L28
https://github.com/lanmaster53/recon-ng-marketplace/blob/bab663d0d7b5bc4f8d55169fcb0b945b716abab5/modules/recon/domains-hosts/hackertarget.py#L18
You are comparing object references (`is`) instead of object values (`==`), see https://realpython.com/lessons/warnings-about-dangerous-syntax/

**Comment by lanmaster53** [comment]
This is indeed a new thing in Python 3.8. Recon-ng has not transitioned to Python 3.8 yet, so as long as it's just a warning and doesn't prevent it from running, ignore it for now. It is something that needs to be fixed eventually. Consider Recon-ng to require Python 3.7.

**Comment by lanmaster53** [comment]
Let's leave this open as a reminder to port to Python 3.8. Thanks!
