### ISSUE TITLE
recon/domains-vulnerabilities/xssposed

### ISSUE THREAD

**Issue by MrJester** [lanmaster53/recon-ng-marketplace#32]
Just putting this here so we can get off the spreadsheet

It has moved to openbugbounty.org. This api actually exists on that domain, but the info has changed.

**Comment by ronaldobomfim** [comment]
Hi,
I'm new here and I have experienced some issues to run this module.
Every time I try to execute the referenced module, I receive the following message:

[!] HTTPSConnectionPool(host='www.xssposed.org', port=443)  Max retries exceeded with url  /api/1/search/?domain=globo.com (Caused by SSLError(SSLError("bad handshake  Error([('SSL routines', 'ssl3_get_record', 'wrong version number')])"))).

I already tried to solve this issue follow the troubleshooting in https://github.com/coursera-dl/coursera-dl#sslerror-errno-1-_sslc504-error14094410ssl-routinesssl3_read_bytessslv3-alert-handshake-failure but the error persists.

What I could do to fix it?

**Comment by MrJester** [comment]
If you notice my comment above xssposed no longer exists well atleast not at that URL they have migrated to openbugbounty.org and this module needs to be updated to hit that API endpoint and if there were any changes to the API those would need to be fixed. So this is a broken module at the moment. Always welcome to contribute if you would like to help with that update. Thanks

**Comment by ronaldobomfim** [comment]
Thank you MrJester for the information!

**Comment by cam-barts** [comment]
Submitted for API access. Will close if they grant access.

**Comment by lanmaster53** [comment]
Going to close this by removing the module. Any movement toward openbugbounty should result in a new module anyway. This code will be buried in the commit history if anyone needs it.
