### ISSUE TITLE
recon/netblocks-companies/whois_orgs

### ISSUE THREAD

**Issue by photoemulator** [lanmaster53/recon-ng-marketplace#40]
issue with running module.  
![Screenshot from 2019-07-01 15-21-12](https://user-images.githubusercontent.com/11272840/60461936-0181ad00-9c16-11e9-9735-8e1bc60bb1ad.png)
![Screenshot from 2019-07-01 15-27-08](https://user-images.githubusercontent.com/11272840/60461937-0181ad00-9c16-11e9-84fc-28f4594d5a15.png)

**Comment by MrJester** [comment]
So this module is looking at netblocks. So you would have to provide it a netblock such as 8.8.8.8/32 for the module to function as it should. I do think this should be erroring more gracefully so I will look into that.

**Comment by photoemulator** [comment]
Thanks.  Should I install netblocks in the meantime?

**Comment by MrJester** [comment]
Well, I'm not sure of your end goal but if you just have a domain you would want to start with the recon/domain-* modules to start collecting more data then you migrate from there to other types of modules. If you want to discuss this more though you should join us on Slack as there are more people that can help with this and it won't add more issues here on Github. Info about joining slack https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#help

**Comment by lanmaster53** [comment]
This is a great example as to why we need https://github.com/lanmaster53/recon-ng/issues/34. It will go a long way to helping with issues like these. The error you are seeing is the result of debug level verbosity being enabled. If you had a verbosity of 1, it wouldn't look that bad. But yeah, it should be unnecessary for developers to have to account for every possible input. That's what validation is for. Thanks for this. Closing this one since it was user error and not an issue here specifically.
