### ISSUE TITLE
recon/domains-hosts/findsubdomains not returning results

### ISSUE THREAD

**Issue by lanmaster53** [lanmaster53/recon-ng-marketplace#73]
**Module Name**
Which module is affected?
https://github.com/lanmaster53/recon-ng-marketplace/tree/master/modules/recon/domains-hosts/findsubdomains.py

**Bug Description**
The website clearly finds subdomains but the module returns nothing. I debugged and apparently the site has changed and the parser is failing to extract subdomains. There is some work to be done here because it paginates too, which this module didn't do.

**Steps to Reproduce**
See above.

**Expected Behavior**
Return the same results as the web interface.

**Comment by MrJester** [comment]
So looks like the pagenation has moved behind a login page. There is an API but it is limited to 100 requests per month. We could migrate this to take advantage of the API.

**Comment by MrJester** [comment]
They have also moved to spyse.com

**Comment by leebaird** [comment]
**Bug Description**
[!] Error retrieving results.

**Steps to Reproduce**
1. modules load recon/domains-hosts/findsubdomains
2. goptions set VERBOSITY 2
3. run

**Expected Behavior**
Returns results.

**Current Behavior**
[*] No validator required.
[*] DATABASE => /root/.recon-ng/workspaces/acme.org/data.db
[*] QUERY => SELECT DISTINCT domain FROM domains WHERE domain IS NOT NULL
[*] DATABASE => /root/.recon-ng/workspaces/acme.org/data.db
[*] QUERY => INSERT OR REPLACE INTO dashboard (module, runs) VALUES ('recon/domains-hosts/findsubdomains', COALESCE((SELECT runs FROM dashboard WHERE module='recon/domains-hosts/findsubdomains')+1, 1))

----------
ACME.ORG
----------
[*] ========================= REQUEST =========================
url:    https://spyse.com/search/subdomain
method: GET /search/subdomain
header: User-Agent: Recon-ng/v5
header: Accept-Encoding: gzip, deflate
header: Accept: */*
header: Connection: keep-alive
[*] ========================= RESPONSE =========================
status: 403 Forbidden
header: Date: Sun, 05 Jul 2020 01:19:06 GMT
header: Content-Type: text/html; charset=UTF-8
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: Set-Cookie: __cfduid=d8d4c23d848ea94ccb7f44dbb6429f61d1593911946; expires=Tue, 04-Aug-20 01:19:06 GMT; path=/; domain=.spyse.com; HttpOnly; SameSite=Lax; Secure
header: Cache-Control: max-age=15
header: Expires: Sun, 05 Jul 2020 01:19:21 GMT
header: X-Frame-Options: SAMEORIGIN
header: cf-request-id: 03be2744bc00000d1e2ca7c200000001
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Vary: Accept-Encoding
header: Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
header: Server: cloudflare
header: CF-RAY: 5add41812d370d1e-ATL
header: Content-Encoding: gzip
body:   b'<!DOCTYPE html>\n\n\n\n <html class="no-js" lang="en-US"> \n<head>\n<title>Attention Required! | Cloudflare</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />\n\n<style type="text/css">body{margin:0;padding:0}</style>\n\n\n<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>\n<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>\n\n\n\n</head>\n<body>\n  <div id="cf-wrapper">\n    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>\n    <div id="cf-error-details" class="cf-error-details-wrapper">\n      <div class="cf-wrapper cf-header cf-error-overview">\n        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>\n        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> spyse.com</h2>\n      </div>\n\n      <div class="cf-section cf-highlight">\n        <div class="cf-wrapper">\n          <div class="cf-screenshot-container cf-screenshot-full">\n            \n              <span class="cf-no-screenshot error"></span>\n            \n          </div>\n        </div>\n      </div>\n\n      <div class="cf-section cf-wrapper">\n        <div class="cf-columns two">\n          <div class="cf-column">\n            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>\n\n            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>\n          </div>\n\n          <div class="cf-column">\n            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>\n\n            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>\n          </div>\n        </div>\n      </div>\n\n      <div class="cf-error-footer cf-wrapper">\n  <p>\n    <span class="cf-footer-item">Cloudflare Ray ID: <strong>5add41812d370d1e</strong></span>\n    <span class="cf-footer-separator">&bull;</span>\n    <span class="cf-footer-item"><span>Your IP</span>: 68.52.28.218</span>\n    <span class="cf-footer-separator">&bull;</span>\n    <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>\n    \n    <span class="cf-footer-separator">&bull;</span>\n    <span class="cf-footer-item">\n      <select id="lang-selector">\n        <option value="">Select a Language</option>\n        <option value="en">English</option>\n        <option value="es">Espa\xc3\xb1ol</option>\n      </select>\n    </span>\n    \n  </p>\n</div>\n\n\n    </div>\n  </div>\n\n  <script type="text/javascript">\n  window._cf_translation = {};\n  window._cf_translation.locale = \'en\';\n  window._cf_translation.blobs = {};\n</script>\n\n</body>\n</html>\n'

**Comment by leebaird** [comment]
When I access the website, I'm not being blocked.

**Comment by MrJester** [comment]
Look at the comments above. They have moved to a new domain this module needs to be updated.

**Comment by MrJester** [comment]
Spyse reaches out and is getting me a test account so I’ll be updating this module once I get setup with that account.bIll prob shift to creating a new module and retiring this one.
